name: DevSecOps Pipeline (Semgrep)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Semgrep Security Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
